unstable_features = true
group_imports = "StdExternalCrate"
tab_spaces = 2
type_punctuation_density = "Compressed"
use_field_init_shorthand = true
where_single_line = true
wrap_comments = true
comment_width = 94
